<?php

namespace AssociationBundle\Repository;;

/**
 * formatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class campementRepository extends \Doctrine\ORM\EntityRepository
{

    public function myfindid($id)
    {
        $qb = $this->createQueryBuilder('c');
        $query =     $qb->where('c.idassociation = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $results = $query->getResult();
    }

}
