<?php

namespace NecessiteuxBundle\Repository;

/**
 * DemandeAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeRepository extends \Doctrine\ORM\EntityRepository
{

}
