<?php

namespace NecessiteuxBundle\Repository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class feedbackRepository extends \Doctrine\ORM\EntityRepository
{

}
