<?php

namespace BenevoleBundle\Repository;

/**
 * EventfeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventfeedbackRepository extends \Doctrine\ORM\EntityRepository
{
}
